import { useCallback, useEffect, useState } from 'react'
import { AlertCircle, ArrowLeft, Check, CheckCircle2, ChevronDown, Clock3, Download, MessageSquare, ShieldCheck } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { closeRfq, decideRfq, getRfqDetail, resolveGate, submitRfq } from '../lib/rfqApi'
import { exportQuotesToExcel } from '../lib/exportToExcel'
import './RfqDetail.css'

const STATUS = { draft: 'Draft', out_for_quotes: 'Collecting quotes', quotes_in: 'Quotes received', negotiating: 'Negotiating', awaiting_approval: 'Needs approval', decided: 'Decision recorded', closed: 'Closed' }
const STEPS = ['draft', 'out_for_quotes', 'quotes_in', 'negotiating', 'awaiting_approval', 'decided', 'closed']
const GATE_LABEL = { supplier_list: 'Supplier list approval', price: 'Negotiated price approval', winner: 'Winning supplier approval' }
const SPEC_MATCH = { match: 'Matches request', mismatch: 'Does not match', unknown: 'Not verified' }

export function RfqDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  const [refreshing, setRefreshing] = useState(false)

  const load = useCallback(async () => {
    try { setData(await getRfqDetail(id)); setError('') } catch (err) { setError(err.message) } finally { setRefreshing(false) }
  }, [id])
  useEffect(() => { load(); const timer = setInterval(load, 10000); return () => clearInterval(timer) }, [load])

  if (error && !data) return <div className="rfq-page"><button className="back-link" onClick={() => navigate('/rfqs')}><ArrowLeft size={15} /> Work queue</button><div className="page-error"><AlertCircle size={20} /><strong>Could not load this request</strong><span>{error}</span><button className="secondary-button" onClick={load}>Try again</button></div></div>
  if (!data) return <div className="rfq-page"><div className="loading-state">Loading procurement request…</div></div>

  const { rfq, negotiations, quotes, pendingGates } = data
  const currentIndex = Math.max(0, STEPS.indexOf(rfq.status))
  const needsAttention = pendingGates.length > 0

  async function closeRequest() { try { await closeRfq(rfq.id); load() } catch (err) { setError(err.message) } }
  return (
    <div className="rfq-page">
      <div className="rfq-toolbar"><button className="back-link" onClick={() => navigate('/rfqs')}><ArrowLeft size={15} /> Work queue</button><button className="refresh-link" onClick={() => { setRefreshing(true); load() }} disabled={refreshing}><Clock3 size={14} /> {refreshing ? 'Refreshing…' : 'Updated automatically'}</button></div>
      {error && <div className="inline-alert inline-alert--error"><AlertCircle size={16} /> {error}</div>}
      <header className="rfq-heading"><div><p className="page-kicker">Procurement request</p><h1>{rfq.product}{rfq.grade && <span> · {rfq.grade}</span>}</h1><p className="rfq-id">Request {rfq.id.slice(0, 8)} · Last updated {new Date(rfq.updatedAt || rfq.createdAt).toLocaleString()}</p></div><span className={`rfq-status rfq-status--${rfq.status}`}>{STATUS[rfq.status] ?? rfq.status}</span></header>
      <WorkflowTimeline status={rfq.status} currentIndex={currentIndex} />
      <div className="rfq-layout">
        <main className="rfq-main">
          {needsAttention && <section className="decision-panel"><div className="decision-panel__heading"><div><p className="card-kicker">Your decision is required</p><h2>Review before Wad continues</h2></div><ShieldCheck size={22} /></div><p className="decision-panel__intro">Check the evidence below, then approve, counter, or reject the proposed terms. Your decision will be recorded in the procurement history.</p>{pendingGates.map((gate) => <GateCard key={gate.id} gate={gate} rfq={rfq} onResolved={load} />)}</section>}
          {rfq.status === 'draft' && <SupplierForm rfqId={rfq.id} onSent={load} />}
          <ComparisonTable rfq={rfq} quotes={quotes} onDecided={load} />
          {negotiations.length > 0 && <Transcripts negotiations={negotiations} />}
          {rfq.status === 'decided' && <div className="completion-panel"><CheckCircle2 size={19} /><div><strong>Supplier decision recorded</strong><span>Close this request when the purchasing record is complete.</span></div><button className="secondary-button" onClick={closeRequest}>Close request</button></div>}
        </main>
        <aside className="rfq-aside"><section className="workspace-card"><div className="section-heading"><div><p className="card-kicker">Request specification</p><h2>What is being procured</h2></div></div><SpecGrid rfq={rfq} /></section><section className="workspace-card"><div className="section-heading"><div><p className="card-kicker">Decision guidance</p><h2>What to check</h2></div></div><ul className="guidance-list"><li><Check size={14} /> Specification match</li><li><Check size={14} /> Total price and delivery</li><li><Check size={14} /> Supplier and compliance risk</li><li><Check size={14} /> Terms you can approve</li></ul></section></aside>
      </div>
    </div>
  )
}

function WorkflowTimeline({ status, currentIndex }) { return <section className="workflow"><div className="workflow__top"><div><p className="card-kicker">Workflow progress</p><strong>{STATUS[status] ?? status}</strong></div><span>Step {currentIndex + 1} of {STEPS.length}</span></div><div className="workflow__steps">{STEPS.map((step, i) => <div className={`workflow__step ${i < currentIndex ? 'is-done' : ''} ${i === currentIndex ? 'is-current' : ''}`} key={step}><span>{i < currentIndex ? <Check size={12} /> : i + 1}</span><small>{STATUS[step]}</small></div>)}</div></section> }

function SpecGrid({ rfq }) { const fields = [['Quantity', rfq.quantity], ['Packaging', rfq.packaging], ['Deliver to', rfq.deliveryLocation], ['Needed by', rfq.neededBy?.slice(0, 10)], ['Target price', rfq.targetPrice], ['Currency', rfq.currency]].filter(([, value]) => value); return <div className="spec-list">{fields.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div> }

function SupplierForm({ rfqId, onSent }) { const [rows, setRows] = useState([{ supplier: '', phone: '' }]); const [state, setState] = useState({ busy: false, error: '' }); const update = (i, key, value) => setRows((prev) => prev.map((row, idx) => idx === i ? { ...row, [key]: value } : row)); async function send() { const suppliers = rows.filter((row) => row.supplier.trim() && row.phone.trim()); if (!suppliers.length) { setState({ busy: false, error: 'Add at least one supplier with a phone number.' }); return } setState({ busy: true, error: '' }); try { await submitRfq(rfqId, suppliers); onSent() } catch (err) { setState({ busy: false, error: err.message }) } } return <section className="workspace-card rfq-section"><div className="section-heading"><div><p className="card-kicker">Next action</p><h2>Confirm suppliers to contact</h2><p>Wad will contact the suppliers below and negotiate within the terms you approve.</p></div></div><div className="supplier-form">{rows.map((row, i) => <div className="supplier-row" key={i}><input value={row.supplier} onChange={(e) => update(i, 'supplier', e.target.value)} placeholder="Supplier name" aria-label="Supplier name" /><input value={row.phone} onChange={(e) => update(i, 'phone', e.target.value)} placeholder="WhatsApp number" aria-label="Supplier WhatsApp number" /></div>)}{state.error && <div className="inline-alert inline-alert--error"><AlertCircle size={16} /> {state.error}</div>}<div className="card-actions"><button className="secondary-button" onClick={() => setRows((prev) => [...prev, { supplier: '', phone: '' }])}>+ Add supplier</button><button className="primary-button" disabled={state.busy} onClick={send}>{state.busy ? 'Sending…' : 'Start supplier outreach'}</button></div></div></section> }

function GateCard({ gate, rfq, onResolved }) { const [countering, setCountering] = useState(false); const [note, setNote] = useState(''); const [state, setState] = useState({ busy: false, error: '' }); const proposal = gate.proposal ?? {}; async function act(action) { if (action === 'counter' && !note.trim()) { setCountering(true); return } setState({ busy: true, error: '' }); try { await resolveGate(gate.id, action, note.trim() || undefined); onResolved() } catch (err) { setState({ busy: false, error: err.message }) } } const evidence = [proposal.price ? `Proposed price: ${proposal.price}` : 'Price not available', proposal.moq ? `MOQ: ${proposal.moq}` : 'MOQ not available', proposal.leadTime ? `Lead time: ${proposal.leadTime}` : 'Lead time not available', rfq.targetPrice ? `Target: ${rfq.currency} ${rfq.targetPrice}` : 'No target price recorded']; return <div className="gate-card"><div className="gate-card__top"><strong>{GATE_LABEL[gate.gateType] ?? 'Approval required'}</strong>{proposal.supplier && <span>{proposal.supplier}</span>}</div>{proposal.summary && <p>{proposal.summary}</p>}<div className="approval-evidence"><span>Decision evidence</span><ul>{evidence.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="term-grid">{proposal.price && <div><span>Proposed price</span><strong>{proposal.price}</strong></div>}{proposal.moq && <div><span>MOQ</span><strong>{proposal.moq}</strong></div>}{proposal.leadTime && <div><span>Lead time</span><strong>{proposal.leadTime}</strong></div>}</div>{countering && <textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="What should Wad negotiate for?" autoFocus />}{state.error && <div className="inline-alert inline-alert--error"><AlertCircle size={16} /> {state.error}</div>}<div className="card-actions"><button className="secondary-button" disabled={state.busy} onClick={() => act('reject')}>Reject</button><button className="secondary-button" disabled={state.busy} onClick={() => act('counter')}>{countering ? 'Send counter' : 'Counter'}</button><button className="primary-button" disabled={state.busy} onClick={() => act('approve')}>Approve and commit</button></div></div> }

function ComparisonTable({ rfq, quotes, onDecided }) { const complete = quotes.filter((quote) => quote.price || quote.leadTime || quote.specMatch !== 'unknown').length; const matched = quotes.filter((quote) => quote.specMatch === 'match').length; return <section className="workspace-card rfq-section"><div className="section-heading"><div><p className="card-kicker">Supplier evidence</p><h2>Compare quotes</h2><p>{quotes.length ? `${quotes.length} supplier response${quotes.length === 1 ? '' : 's'} received. Check the evidence before selecting.` : 'Quotes will appear here as suppliers reply.'}</p></div>{quotes.length > 0 && <button className="secondary-button" onClick={() => exportQuotesToExcel(rfq, quotes)}><Download size={14} /> Export</button>}</div>{quotes.length === 0 ? <div className="empty-state"><MessageSquare size={20} /><strong>Waiting for supplier responses</strong><span>Wad will update this comparison as replies arrive.</span></div> : <><div className="comparison-summary"><div><span>Responses with usable terms</span><strong>{complete} / {quotes.length}</strong></div><div><span>Specification matches</span><strong>{matched} / {quotes.length}</strong></div><div><span>Target price</span><strong>{rfq.targetPrice ? `${rfq.currency} ${rfq.targetPrice}` : 'Not set'}</strong></div></div><div className="comparison-scroll"><table className="comparison-table"><thead><tr><th>Supplier</th><th>Price</th><th>MOQ</th><th>Lead time</th><th>Payment</th><th>Specification</th><th>Decision</th></tr></thead><tbody>{quotes.map((quote) => { const won = rfq.winningQuoteId === quote.id; const missing = [!quote.price && 'price', !quote.leadTime && 'lead time', quote.specMatch === 'unknown' && 'specification'].filter(Boolean); return <tr className={won ? 'is-winner' : ''} key={quote.id}><td><strong>{quote.supplier}</strong><small>{quote.channel}</small></td><td>{quote.price ?? '—'}</td><td>{quote.moq ?? '—'}</td><td>{quote.leadTime ?? '—'}</td><td>{quote.paymentTerms ?? '—'}</td><td><span className={`spec-result spec-result--${quote.specMatch}`}>{SPEC_MATCH[quote.specMatch] ?? 'Not verified'}</span>{quote.specMatchNote && <small className="cell-note">{quote.specMatchNote}</small>}{missing.length > 0 && <small className="cell-note cell-note--warning">Missing: {missing.join(', ')}</small>}</td><td>{won ? <span className="winner-label"><Check size={14} /> Selected</span> : rfq.status !== 'closed' && <button className="text-button" onClick={async () => { try { await decideRfq(rfq.id, quote.id); onDecided() } catch {} }}>Select</button>}</td></tr> })}</tbody></table></div></>}</section> }

function Transcripts({ negotiations }) { return <section className="workspace-card rfq-section"><div className="section-heading"><div><p className="card-kicker">Traceability</p><h2>Supplier conversations</h2></div></div><div className="transcript-list">{negotiations.map((negotiation) => <details key={negotiation.id}><summary><span>{negotiation.supplier}</span><span>{negotiation.status.replace(/_/g, ' ')}</span><ChevronDown size={15} /></summary><div className="messages">{negotiation.messages.length === 0 ? <p className="empty-state">No messages yet.</p> : negotiation.messages.map((message, i) => <div className={`message message--${message.role}`} key={i}>{message.text}</div>)}</div></details>)}</div></section> }
